### ISSUE TITLE
请问如何从高频头那边读数据？有没有相关数据说明

### ISSUE THREAD

**Issue by zhuwei** [danxdz/simpleTx_esp32#1]

**Comment by danxdz** [comment]
English please?

**Comment by zhuwei** [comment]
"Simple_TX.ino" line 204 error.

**Comment by danxdz** [comment]
Hum i will check.. but may need to close some function '}'..
This is an work in progress.. i have made several changes on local code (like half duplex working correctly... but not yet clean tou update and not gonna be next days, bc im tii busy atm..

**Comment by zhuwei** [comment]
Thank you. I'll study it

**Comment by danxdz** [comment]
just updated, linkstats are working and output on serial

**Comment by zhuwei** [comment]
nice!!!
