### ISSUE TITLE
stuck on "loading" and "no rx" screen

### ISSUE THREAD

**Issue by satyanvesi** [danxdz/simpleTx_esp32#13]
so here is 2 stuck on screen issue
(1)on main screen when i press enter it displays "DIY900 TX loading" also same is shown debug on debug UART.In this case RX is connected and all work fine.
(2)first i turn on the TX(simpleTx-esp32) it displays "no RX".than after if turn On RX,RX gets connected but display still stays stuck on "no Rx".now at this point if i press reset on my esp32dev(simpleTx-esp32) board it displays main screen with all rssi and all data.

**Comment by danxdz** [comment]
Hi, thanks for your  feedback and I'll definitely take a look at the code as soon as possible.

**Comment by danxdz** [comment]
you could retry, i think its fixed now..
