### ISSUE TITLE
How to wire the cable?

### ISSUE THREAD

**Issue by iamfaith** [danxdz/simpleTx_esp32#4]
Nice project! I am not good at hardware.
Could you please tell me how to connect the esp32 module with the elrs TX ?

**Comment by danxdz** [comment]
Hi, thanks.. you need to connect pin 13 from esp32 to elrs tx.. tell me if you need more details

**Comment by danxdz** [comment]
It works?

**Comment by erstec** [comment]
@danxdz 
It would be nice to create some preliminary schematics. I believe you have someting "live and working" on table already. What do you think?
Contact me please.

**Comment by danxdz** [comment]
yes its working on bench.. im finishing some schematics.. i think i can post a preview today

**Comment by danxdz** [comment]
https://github.com/danxdz/simpleTx_esp32/wiki

say some if you some problem
